const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I told my computer I needed a break. Now it won't stop sending me vacation ads.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "I'm on a whiskey diet. I've lost three days already!",
    "I'm friends with 25 letters of the alphabet. I don't know why.",
    "I used to play piano by ear, but now I use my hands.",
    "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you!'",
    "I would tell you a joke about UDP, but you might not get it.",
    "Why was the math book sad? Because it had too many problems.",
    "I'm trying to organize a hide and seek competition, but it's difficult to find good players, you know?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I'm reading a book on the history of glue. I just can't seem to put it down.",
    "I told my wife she was average. She was mean!",
    "Why don't seagulls fly over the bay? Because then they'd be bagels!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "What do you call fake spaghetti? An impasta!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "I told my computer I needed a break. Now it won't stop sending me vacation ads.",
    "I'm on a whiskey diet. I've lost three days already!",
    "I'm friends with 25 letters of the alphabet. I don't know why.",
    "I used to play piano by ear, but now I use my hands.",
    "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you!'",
    "I would tell you a joke about UDP, but you might not get it.",
    "I'm trying to organize a hide and seek competition, but it's difficult to find good players, you know?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I'm reading a book on the history of glue. I just can't seem to put it down.",
    "I told my wife she was average. She was mean!",
    "Why don't seagulls fly over the bay? Because then they'd be bagels!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? Because it had too many problems.",
    "I'm trying to organize a hide and seek competition, but it's difficult to find good players, you know?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I'm reading a book on the history of glue. I just can't seem to put it down.",
    "I told my wife she was average. She was mean!",
    "Why don't seagulls fly over the bay? Because then they'd be bagels!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? Because it had too many problems.",
    "I'm trying to organize a hide and seek competition, but it's difficult to find good players, you know?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I'm reading a book on the history of glue. I just can't seem to put it down.",
    "I told my wife she was average. She was mean!",
    "Why don't seagulls fly over the bay? Because then they'd be bagels!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? Because it had too many problems.",
    "I'm trying to organize a hide and seek competition, but it's difficult to find good players, you know?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I'm reading a book on the history of glue. I just can't seem to put it down.",
   

];

function getRandomJoke() {
    return jokes[Math.floor(Math.random() * jokes.length)];
}

function displayJoke() {
    const jokeDisplay = document.getElementById("jokeDisplay");
    jokeDisplay.textContent = getRandomJoke();
}

displayJoke(); // Display joke immediately on page load

setInterval(displayJoke, 10000); // Display a new joke every 10 seconds
